version: "1.0"
stages:
  - name: build
    steps:
      - name: Install Dependencies
        command: echo "Installing dependencies..."
        image: alpine:latest
        working_dir: /app
        env:
          NODE_ENV: development
      - name: Build Project
        command: echo "Building project..."
        image: alpine:latest
        working_dir: /app
        env:
          NODE_ENV: production
        depends_on:
          - Install Dependencies
    parallel: false
    depends_on: []
  - name: test
    steps:
      - name: Run Unit Tests
        command: echo "Running unit tests..."
        image: alpine:latest
        working_dir: /app
        env:
          NODE_ENV: development
      - name: Run Linting
        command: echo "Running linting..."
        image: alpine:latest
        working_dir: /app
        env:
          NODE_ENV: development
    parallel: true
    depends_on:
      - build
cache:
  enabled: true
  directories:
    - /app/node_modules
    - /app/.cache
secrets:
  - name: API_TOKEN
    env_var: FORGE_API_TOKEN