version: "1.0"
stages:
  - name: setup
    steps:
      - name: Install Dependencies
        command: npm install
        image: node:16-alpine
        working_dir: /workspace
    parallel: false
  
  - name: test
    steps:
      - name: Lint
        command: npm run lint
        image: node:16-alpine
        working_dir: /workspace
      - name: Unit Tests
        command: npm test
        image: node:16-alpine
        working_dir: /workspace
    parallel: true
    depends_on:
      - setup
  
  - name: build
    steps:
      - name: Build Application
        command: npm run build
        image: node:16-alpine
        working_dir: /workspace
        env:
          NODE_ENV: production
    depends_on:
      - test

cache:
  enabled: true
  directories:
    - /workspace/node_modules
